### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by robin7331** [ebaauw/homebridge-lib#1]
Hey there,

neat idea! 
While digging through the wiki I figured it would be awesome to have some sort of example platform implemented with this library.

Do you have any code that you'd like to share?

Cheers!

**Comment by robin7331** [comment]
Scratch that.
No idea why I did not see that in your readme :/

**Comment by robin7331** [comment]
Sorry, I have to reopen this since I saw that you only provided some example code for the index.js and the Platform.js. 
Is there any example on how you used this to implement a platform with accessories?

**Comment by robin7331** [comment]
Sorry, I have to reopen this since I saw that you only provided some example code for the index.js and the Platform.js. 
Is there any example on how you used this to implement a platform with accessories?

**Comment by ebaauw** [comment]
This is still very much work in progress.  You might want to check the [1.0 branch of homebridge-hue](https://github.com/ebaauw/homebridge-hue/tree/v1.0), but that is only functional for discovering the bridge(s) and creating users - no accessories for lights or sensors yet.

**Comment by robin7331** [comment]
Perfect. Thanks!
