### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-lib#12]
Hello, Erik,

i just noticed that when calling npm list -g --depth=0 on homebridge-lib an error is displayed. I installed Homebridge-lib again Error is still present.

King Regards
Nastra

**Comment by Nastras** [comment]
<img width="871" alt="Bildschirmfoto 2019-07-21 um 07 00 45" src="https://user-images.githubusercontent.com/27686185/61587180-4b124780-ab85-11e9-9ae1-5d45ababd46a.png">

**Comment by Nastras** [comment]
Could it be that version homebridge-lib@4.3.0 is too new for homebridge-hue@0.11.29. That's how I understand the error?

**Comment by ebaauw** [comment]
Yes.  Homebridge-hue doesn’t (yet) use the functionality in homebridge-lib that had breaking changes between v4.2.9 and v4.3.0, so it will work alright with this newer version.

I introduced the peer dependency setup so multiple plugins could share a single instance of homebridge-lib, using fewer system resources.  This way, the plugins share the heartbeat timer and UPnP listener.  I’ve also been fantasising about other shared functionality, like exposing a switch to enable/disable homebridge debug logging dynamically (so you would have to restart homebridge with or without `-D`).

However, the peer dependency setup seems far more challenging that I had anticipated.  While technically fit for purpose, it’s an a-typical setup, too complex for users, and causing too many issues.  I might have to revert to homebridge-lib being a regular dependency, installed with each plugin, and find another way share a single instance, very much like homebridge provides a single instance of HAP-NodeJS to all plugins.

**Comment by Nastras** [comment]
Yes. Homebridge-hue doesn’t (yet) use the functionality in homebridge-lib that had breaking changes between v4.2.9 and v4.3.0, so it will work alright with this newer version.

- That's what I suspected.

I introduced the peer dependency setup so multiple plugins could share a single instance of homebridge-lib, using fewer system resources. This way, the plugins share the heartbeat timer and UPnP listener. I’ve also been fantasising about other shared functionality, like exposing a switch to enable/disable homebridge debug logging dynamically (so you would have to restart homebridge with or without -D).

- I think that's a great idea.

However, the peer dependency setup seems far more challenging that I had anticipated. While technically fit for purpose, it’s an a-typical setup, too complex for users, and causing too many issues. I might have to revert to homebridge-lib being a regular dependency, installed with each plugin, and find another way share a single instance, very much like homebridge provides a single instance of HAP-NodeJS to all plugins.

- I wish I could help you, unfortunately I don't know anything about this topic.  But I want to thank you for the detailed description and your great work in the homebridge project. I hope that you find a solution for the problem!

Greetings Nastra

**Comment by ebaauw** [comment]
Thanks, @Nastras.

**Comment by ebaauw** [comment]
The latest versions of my plugins, once again, list homebridge-lib as regular dependency.

homebridge-lib@4.3.3 can no longer be loaded by Homebridge.  The first plugin loaded also registers homebridge-lib with Homebridge, providing the heartbeat and UPnP listener to the other plugins.
