### ISSUE TITLE
ERROR ERROR LOADING PLUGI

### ISSUE THREAD

**Issue by Sturmhorst** [ebaauw/homebridge-lib#13]
I have the following issue:

`Jul 22 19:26:58 phoscon homebridge[1766]: [7/22/2019, 7:26:58 PM] ====================
Jul 22 19:26:58 phoscon homebridge[1766]: [7/22/2019, 7:26:58 PM] ERROR LOADING PLUGIN homebridge-hue:
Jul 22 19:26:59 phoscon homebridge[1766]: [7/22/2019, 7:26:59 PM] Error: Cannot find module 'homebridge-lib'
Jul 22 19:26:59 phoscon homebridge[1766]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module.require (internal/modules/cjs/loader.js:636:17)
Jul 22 19:26:59 phoscon homebridge[1766]:     at require (internal/modules/cjs/helpers.js:20:18)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:22:23)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module.load (internal/modules/cjs/loader.js:598:32)
Jul 22 19:26:59 phoscon homebridge[1766]:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module.require (internal/modules/cjs/loader.js:636:17)
Jul 22 19:26:59 phoscon homebridge[1766]:     at require (internal/modules/cjs/helpers.js:20:18)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/index.js:8:21)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
Jul 22 19:26:59 phoscon homebridge[1766]:     at Module.load (internal/modules/cjs/loader.js:598:32)
Jul 22 19:26:59 phoscon homebridge[1766]: [7/22/2019, 7:26:59 PM] ====================
`

**Comment by ebaauw** [comment]
Did you install homebridge-lib?  See https://github.com/ebaauw/homebridge-hue#installation

**Comment by Sturmhorst** [comment]
Yes I did!

**Comment by ebaauw** [comment]
How did you install it?  How did you install homebridge-hue?  What is the output of
```
$ ls -al /usr/local/lib/node_modules
```

**Comment by ebaauw** [comment]
Please upgrade to homebridge-hue@0.11.30, which, once again, lists homebridge-lib as peer depencency.
