### ISSUE TITLE
Keyword error

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-lib#14]
Everything works fine, jsut wondering about this Errormessage

`[9/13/2019, 12:32:40 PM] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.`

**Comment by ebaauw** [comment]
Don't install homebridge-lib separately; it's installed with the plugin(s) that use it.

Best uninstall homebrdige-lib and re-install the plugin(s) using it.

**Comment by beatpaul** [comment]
Worked!
Thx!!
