### ISSUE TITLE
Q: what service/characteristic to use for a vibration sensor?

### ISSUE THREAD

**Issue by mrose17** [ebaauw/homebridge-lib#15]
a question somewhat related to this repository:

i've got a sensor that measures vibration in m/s^2 ... i don't see any standard or third-party homekit characteristics that model this.

neither motion sensor nor occupancy sensor really work, but since the sensor also has a motion sensor, i'm thinking of modeling the vibration sensor using an occupancy sensor and setting occupancy detected to true if the G is outside of [0.75, 1.25]

your thoughts?

**Comment by ebaauw** [comment]
I map the Xioami Vibration sensor to a HomeKit motion sensor in homebridge-hue, even though deCONZ exposes it differently.  You could always use a custom characteristic to report acceleration or G.  You can create HomeKit scenes and automations for custom characteristics in e.g. Eve, and recall the scene from Siri or Apple's Home app.

**Comment by mrose17** [comment]
thank you! i think it's best to just fold the motion sensor and vibration sensor into a singe motion detection...
