### ISSUE TITLE
Q: what service/characteristic to use for a power fail sensor

### ISSUE THREAD

**Issue by mrose17** [ebaauw/homebridge-lib#16]
and, as long as i'm asking you random questions @ebaauw , i have a sensor that has two plugs: one is intended to plug into a UPS and the other into a wall outlet. if the power goes out on the wall outlet, it reports that.

what would you recommend for a service/characteristic to model this sensor?

thank you again!

**Comment by ebaauw** [comment]
I don't think there's a standard HomeKit characteristic for power failure, but you could map it to _Status Fault_.  I don't think Apple's Home app would recognise it, though.

**Comment by mrose17** [comment]
i agree that StatusFault probably isn't a winner. i'm thinking that the only thing that comes close is Switch, where power loss is indicated by (On = false)....
