### ISSUE TITLE
Adding new Characteristics for Eve

### ISSUE THREAD

**Issue by ctschach** [ebaauw/homebridge-lib#17]
Hi,

I've found the following Eve Characteristics. Do you like to add them?!

E863F113-079E-48FF-8F27-9C2605A29F52 - Flow Rate
E863F123-079E-48FF-8F27-9C2605A29F52 - Water
E863F128-079E-48FF-8F27-9C2605A29F52 - Water Total
E863F125-079E-48FF-8F27-9C2605A29F52 - Average Temperature

Or should I add it and do a pull request?

**Comment by ebaauw** [comment]
A PR is fine, but I’m happy to add them as well.  I do need the details for this: type, permissions, etc

I think these are used by the Eve Aqua?  What service does it use?
