### ISSUE TITLE
Feature request: expose HAP-NodeJS's UUID.generate function

### ISSUE THREAD

**Issue by Djelibeybi** [ebaauw/homebridge-lib#21]
It would be super peachy keen if HAP-NodeJS `util.uuid.generate` function was exposed via `homebridge-lib`.

**Comment by ebaauw** [comment]
Why do you need it?  homebridge-lib calls it under the hood when creating a new accessory, using the `id` parameter to the `AccessoryDelegate`.

**Comment by Djelibeybi** [comment]
Huh, I didn't realise that. Thanks!
