### ISSUE TITLE
Changes to OptionsParser breaks homebridge-ws locations.

### ISSUE THREAD

**Issue by jonathandann** [ebaauw/homebridge-lib#23]
44996a76f246068340c86f243eaf07db5bf842e5 added a RangeError for paths that do not start with "/".

The homebridge-ws allows one to pass "RedactedCity,GB" as an argument in to "locations". However these are not passed to OpenWeatherMap as resource paths, but as URL parmeters ("q=City,GB"). `WSAccessory` [calls `get(this.resource)` with the location](https://github.com/ebaauw/homebridge-ws/blob/master/lib/WsAccessory.js#L65) passed as an argument.

The changes to OptionsParser might be valid, but if so then homebridge-ws shouldn't be assuming it can pass locations as REST resources.

Sample Homebridge log:
`[Weather] RedactedCity,GB: warning: resource: RedactedCity,GB: not a valid path`

**Comment by ebaauw** [comment]
Did you just (re-)install homebridge-ws?

**Comment by ebaauw** [comment]
Release homebridge-lib@4.5.4; if you re-install homebridge-ws it should work again.

**Comment by jonathandann** [comment]
I’ll be able to test this out tonight. I just happened to reinstal homebridge-ws after your changed was pushed and saw the error.

Thanks for sending out a fix!

**Comment by jonathandann** [comment]
I've just reinstalled `homebridge-ws` and it's all working again. Thanks!
