### ISSUE TITLE
Library failing Homebridge verification 

### ISSUE THREAD

**Issue by Djelibeybi** [ebaauw/homebridge-lib#24]
I'm not sure if you're intending to get your plugins verified, but the following issue is blocking mine: https://github.com/homebridge/verified/issues/11

If you're not planning on submitting for verification, I'll just close my request.

**Comment by ebaauw** [comment]
Yeah seen that, and responded over there.  I think verification is cool, but I'm not sure I agree with (the interpretation) of the "The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node.js v10 and v12" criterium.

**Comment by Djelibeybi** [comment]
Thanks, much appreciated.
