### ISSUE TITLE
Feature request: Dynamically changing log level.

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-lib#26]
I've seen multiple requests on almost all my plugins for a possibility to reduce the amount of logging.  I'm not sure how best to implement this, and would appreciate your thoughts on this.

My dilemma:
- Without any logging, I cannot provide support in case an issue occurs.  So I need a way for the user to to change the level of logging;
- The current mechanisms to change the level of logging involve restarting Homebridge with different command-line parameters (`homebridge -D`) or different environment variables (`DEBUG=* homebridge`).  This has proven to be impractical, if not impossible, for people running Homebridge as a service or in a container;
- I probably need to expose changing the level of logging from within HomeKit.  Or only support people with a recent standard Homebridge installation, including Homebridge Config UI X;
- When exposing the level of logging, what should be the granularity:
  1. Per Homebridge instance?  This would introduce an additional accessory (to set the level of logging), that Apple's Home app would show as _Not Supported_.  Also this seems too coarse-grained, as typically you only want to enable logging for the plugin (presumably) causing the issue;
  2. Per plugin?  This would introduce an additional accessory per plugin, that Apple's Home app would should as _Not Supported_.  For Homebridge Hue, I would actually re-use the current bridge/gateway accessories;
  3. Per accessory?  This would introduce an additional characteristic to each accessory.  Or maybe hack something around cycling through the various levels on _Identify_?

As indicated above, please provide your thoughts, commenting to this issue.

**Comment by jojost1** [comment]
I like the way [homebridge-pihole](https://github.com/arendruni/homebridge-pihole) implements this with a custom setting. Not sure how it works from a technical perspective, but might be worth checking into.

![D67CD2DA-285C-4FBC-AA11-43FD728BED1C](https://user-images.githubusercontent.com/8880568/80992946-8d69f400-8e3a-11ea-8254-75000a4d28cd.jpeg)

**Comment by jojost1** [comment]
I like the way [homebridge-pihole](https://github.com/arendruni/homebridge-pihole) implements this with a custom setting. Not sure how it works from a technical perspective, but might be worth checking into.
![16EC52C0-D210-47AB-A4DE-451A902B385C](https://user-images.githubusercontent.com/8880568/80993120-d15cf900-8e3a-11ea-8a31-b366500eed85.jpeg)

**Comment by mshulman** [comment]
The simplest would be to have a "debuglevel" : "none" | "error" | "warn" | "info" | "debug" 

in the config.json for the plugin.

**Comment by ebaauw** [comment]
Sorry @jojost1 , @mshulman a config.json setting is not what I meant by "dynamic".  I want users to be able to change the log level without having to restart Homebridge.

There's no way in hell that I will support disabling error and warning messages.

**Comment by mshulman** [comment]
I wasn’t advocating removing error and warning messages.

The levels are additive. Error is only error. Warning is error + error. Info is info + warning + error.

-ms


On May 5, 2020, at 3:23 AM, Erik Baauw <notifications@github.com> wrote:

﻿

Sorry @jojost1<https://github.com/jojost1> , @mshulman<https://github.com/mshulman> a config.json setting is not what I meant by "dynamic". I want users to be able to change the log level without having to restart Homebridge.

There's no way in hell that I will support disabling error and warning messages.

**Comment by BobCarver** [comment]
A different way to do this would be to have a side file with whatever debug configuration you need/want. In your plugin you would install a listener for a signal.  When it receives that signal it loads the side file which then setup up whatever logging you need.  So the user would need to create the side file in a standard location.  Find the PID of the Homebridge and then use the LINUX 'kill' command to send a signal to that PID.  I am not sure how this would be done with containers - but I assume you can 'ssh' into a container.

**Comment by jojost1** [comment]
Personally I really wouldn't mind restarting homebridge to change log level, most plugins I have installed require a restart when changing it.

**Comment by johnluber** [comment]
I don't mind at all having to restart homebridge to change the logging.  That would be pretty straightforward to do.  

I like mshulman's option as that is pretty normal.

Another option would be to be able to specify where the log goes and then savvy users could set it to /dev/null for normal operations and point it back to a regular file for troubleshooting.

**Comment by ebaauw** [comment]
In Homebridge RPi [v1.1.0](https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.0), and Homebridge WS [v2.3.1](https://github.com/ebaauw/homebridge-ws/releases).

**Comment by ebaauw** [comment]
The setting of logLevel through _Identify_ isn't working out.  On pairing, Eve (and I suppose Home) issue _Identify_ multiple times for accessories with _Lightbulb_ services (to select scenes, or whatever).

So I will be exposing _Log Level_ characteristics and remove setting it through _Identify_.

I also find that setting per accessory is too fine grained from a usage perspective. In Homebridge RPi, I will create a single setting per Pi (for the Pi accessory and all linked GPIO accessories); for Homebridge WS, I will create a setting per Location (for the Location and the Forecasts accessory).

**Comment by jojost1** [comment]
The identify-method works for me with only 1 Pi, but I agree a characteristic would be nicer. Thanks and good job!

**Comment by ebaauw** [comment]
It's easier to manage as a characteristic, using the _Types_ window in Eve (from my dev environment):

![IMG_0203](https://user-images.githubusercontent.com/22179355/82067265-c3c43080-96d0-11ea-9e79-a5740cfe91aa.png)

**Comment by 350d** [comment]
Hello! I've downloaded latest EVE app on my iPhone but can't find any LogLevel options in TYPES or on any devices I've checked (bridges, lights). How to change the log level these days?
