### ISSUE TITLE
Is there a way to disable/suppress the heartbeat drift messages?

### ISSUE THREAD

**Issue by Djelibeybi** [ebaauw/homebridge-lib#27]
My plugin leverages `homebridge-lib` but it doesn't use/need the heartbeat after the initial init. Is there a way I can suppress the `warning: heartbeat 3395, drift 275` style messages that are emitted during normal operation?

**Comment by ebaauw** [comment]
No.  An incidental message (and some repeated during startup) isn't too bad.  If you're seeing these structurally, some plugin is blocking the event loop, probably doing synchronous I/O.

**Comment by Djelibeybi** [comment]
It would be nice to be able to shift the priority of these messages though (or add content/context to them programatically). For plugins that don't use the heartbeat, it can be confusing to users.
