### ISSUE TITLE
StatelessProgrammableSwitches no longer working properly

### ISSUE THREAD

**Issue by Djelibeybi** [ebaauw/homebridge-lib#31]
I'm not sure if this is a bug with `homebridge-lib` or if it's upstream in Homebridge, so I'm hoping you can help debug it. I [wrote a super simple plugin](https://github.com/Djelibeybi/homebridge-button-platform) that exposes a single `StatelessProgrammableSwitch` service per accessory. 

[One of my users reported](https://github.com/Djelibeybi/homebridge-button-platform/issues/31) that Homebridge is only triggering an event if  `Characteristic.ProgrammableSwitchEvent` _changes_, i.e I can't send multiple `Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS` in a row. It'll only trigger on the first one. If I send different events, it works fine.

I can see that `homebridge-lib` is logging this: `platform-test Switch: set Programmable Switch Event to 0` and then `platform-test Switch: set Programmable Switch Event from 0 to 1` so it feels like it's storing the current value on and only setting it if it changes.  I just can't find _where_ this is happening. 

Any ideas?

**Comment by Djelibeybi** [comment]
I've worked out that it's https://github.com/ebaauw/homebridge-lib/blob/master/lib/CharacteristicDelegate.js#L207 not returning `true` for a [`ProgrammableSwitchEvent`](https://developers.homebridge.io/#/characteristic/ProgrammableSwitchEvent) which means that https://github.com/ebaauw/homebridge-lib/blob/master/lib/CharacteristicDelegate.js#L248 will only allow the value to change if the event changes.

**Comment by ebaauw** [comment]
That would be an issue with HAP-NodeJS not setting `eventOnlyCharacteristic`.  I understand this is a manual action, after generating the Service and Characteristics types from the HomeKit Accessory Simulator.  What version of HAP-NodeJS are you using?

**Comment by Djelibeybi** [comment]
Whatever ships with Homebridge 1.3.1, I guess. I'm not doing anything with HAP-NodeJS in particular.

**Comment by ebaauw** [comment]
No response yet from Homebridge collaborators, published v5.0.9 with workaround.

**Comment by Djelibeybi** [comment]
Confirmed that the workaround works for my plugin. Thanks!
