### ISSUE TITLE
Support for AirPressure via Occupancy Sensor?

### ISSUE THREAD

**Issue by NickJLange** [ebaauw/homebridge-lib#32]
Hi -
 I've noticed that mqtt thing is using this library under the covers.  For AirPressure Sensors, people are overriding the name value which seems to work (but is not great). Would you be opposed to a patch to add this as a flag? I'd love to have something versus nothing.

Example: https://github.com/naofireblade/homebridge-weather-plus#readme

**Comment by nVuln** [comment]
feel free to make PR, I'll renew and merge it

**Comment by ebaauw** [comment]
What do you mean by “the name value”?

- The value of the _Name_ characteristic (or any characteristic) is not part of the definitions and should be set by a plugin.  I wouldn’t call this “overriding”.
- The values of services and accessories are maintained from HomeKit.  They’re initialised from the accessory (i.c. the plugin) on pairing, but are no longer accessible over HAP after that.
- The characteristic names are set by Eve, based on the language settings.
