### ISSUE TITLE
Update homebridge-lib

### ISSUE THREAD

**Issue by Bentrama** [ebaauw/homebridge-lib#35]
Hello,
Just a simple question.
I have this on my log :
Warning: latest version: homebridge-lib v5.3.2.
Do you know how I can update it ? 

Thanks a lot

**Comment by ebaauw** [comment]
Usually: update the plugin that uses homebridge-lib.

**Comment by Bentrama** [comment]
I have no plugin available for update. That’s why I was asking.
The plugin that said homebridge-lib has an update is homebridge-deconz.

**Comment by ebaauw** [comment]
Hm, I did update the dependencies, but haven’t yet cut a new version.  Will have a look later this week.

**Comment by fate8383** [comment]
I have the same problem with homebridge-rpi plugin installed, no update in the plugin and I am getting:
[RPi] warning: latest version: homebridge-lib v5.4.0
I guess can be ignored until the next rpi plugin update
