### ISSUE TITLE
Better version check messages

### ISSUE THREAD

**Issue by kernie66** [ebaauw/homebridge-lib#36]
Hi, thanks for your plugins and this lib. I use several of your plugins, and the lib for my own plugins.

Would you consider changing the output of the version checks performed by the lib? So that when a newer version of e.g. NodeJS is used, it does not recommend to update NodeJS but perhaps indicate that the plugin may not work as expected and need to be updated or something. 

So far I haven't seen any strange behaviour when updating NodeJS or Homebridge, but that may just be luck.

Regards,
Kenneth

**Comment by ebaauw** [comment]
What messages are you referring to?  On startup, homebridge-lib only issues warning messages `recommended version:`.

**Comment by kernie66** [comment]
Sorry, my mistake (and sorry for late response). The warning was my fault, not homebridge-lib's.

Thanks again for your great work with all plugins.

Regards,
Kenneth
