### ISSUE TITLE
Eve characteristic AirQualityPPM

### ISSUE THREAD

**Issue by tobekas** [ebaauw/homebridge-lib#8]
Hi,
can you add Eve's characteristic "AirQualityPPM" to `EveHomeKitTypes.js`?

UID is `E863F10B-079E-48FF-8F27-9C2605A29F52` and props are
```
{
    format: this.formats.FLOAT,
    unit: "ppm",
    maxValue: 5000,
    minValue: 0,
    minStep: 1,
    perms: [this.perms.READ, this.perms.NOTIFY]
};
```

see also: https://github.com/simont77/fakegato-history/wiki/Services-and-characteristics-for-Elgato-Eve-devices

**Comment by ebaauw** [comment]
Will be added in v4.0.11.  I'll name it `AirParticulateDensity` for consistency.  There is a standard HomeKit `AirParticulateDensity` characteristic with these properties. There's also a standard `AirQuality` characteristic, which takes an int value from a predefined list (for Excellent, Good, etc) - more like the stars for the new Eve Room (with display).

See https://github.com/KhaosT/HAP-NodeJS/blob/0840ce52cc8015dd75fb21c098bf38cf9611ea4a/lib/gen/HomeKitTypes.js#L70 and https://github.com/KhaosT/HAP-NodeJS/blob/0840ce52cc8015dd75fb21c098bf38cf9611ea4a/lib/gen/HomeKitTypes.js#L114.

Do you know if the the new (with display) and old (without display) Eve Room are still using the custom characteristic?  Eve tends to switch to standard characteristics, once they became available.

**Comment by tobekas** [comment]
Thanks a lot! It's working!
I'm using the custom `AirParticulateDensity `characteristic (E863F10B) in combination with the standard `AirQuality` characteristic. If I used the standard `AirParticulateDensity instead, the history graph is not working anymore.

I have no real "Eve Room" and can't help. But most likely there will be differences. On some screenshots you can see that stars appear even in the Eve app instead of the quality terms.

**Comment by tobekas** [comment]
... and the units are different:
Custom: ppm (max. 5000)
Standard: µg/m^3 (max. 1000)

It is also surprising that the standard `AirParticulateDensity` is not an optional characteristic for service `AirQualitySensor`.

Anyway, this issue is solved. Thank you!
